# Generated by Django 2.0.5 on 2018-08-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('categoria', models.CharField(blank=True, max_length=1, null=True, verbose_name='Categoria')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Profesion',
                'verbose_name_plural': 'profesiones',
                'ordering': ['nombre'],
            },
        ),
    ]
