# Generated by Django 2.1.1 on 2018-10-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesiones', '0002_auto_20181007_2204'),
    ]

    operations = [
    ]
