# Generated by Django 2.0.5 on 2018-08-13 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10, unique=True, verbose_name='RUN')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=30, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=12, null=True, verbose_name='Número de teléfono')),
                ('anexo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Anexo')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('fecha_induccion', models.DateField(blank=True, null=True, verbose_name='Fecha de inducción')),
                ('contrato', models.CharField(blank=True, choices=[('HO', 'HONORARIO'), ('CO', 'CONTRATA'), ('PL', 'PLANTA')], max_length=2, null=True, verbose_name='Tipo de contrato')),
                ('relacion', models.CharField(blank=True, choices=[('PE', 'PERMANENTE'), ('TR', 'TRANSITORIO')], max_length=2, null=True, verbose_name='Tipo de relación')),
                ('estado', models.CharField(blank=True, choices=[('VI', 'VINCULADO'), ('DV', 'DESVINCULADO')], max_length=2, null=True, verbose_name='Estado')),
                ('numero_registro', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de registro')),
                ('dias_administrativos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dias administrativos')),
                ('feridos_legales', models.PositiveIntegerField(blank=True, null=True, verbose_name='Feriados Legales')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionario', verbose_name='Foto')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesiones.Profesion', verbose_name='Profesión')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['creado'],
            },
        ),
    ]
