# Generated by Django 2.1 on 2018-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='run',
            field=models.CharField(max_length=9, unique=True, verbose_name='RUN'),
        ),
    ]
