# Generated by Django 2.1.3 on 2018-11-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20180927_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='key',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='contrato',
            field=models.CharField(blank=True, choices=[('HO', 'HONORARIO'), ('CO', 'CONTRATA'), ('PL', 'PLANTA'), ('EE', 'EXTERNO'), ('PP', 'PROGRAMA')], max_length=2, null=True, verbose_name='Tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dias_administrativos',
            field=models.FloatField(blank=True, null=True, verbose_name='Dias administrativos'),
        ),
    ]
