# Generated by Django 2.1.3 on 2018-11-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20181111_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='key',
            new_name='slug',
        ),
    ]
