# Generated by Django 2.1.3 on 2018-11-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_auto_20181111_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Link'),
        ),
    ]
