# Generated by Django 2.1.3 on 2018-11-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_auto_20181111_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='slug',
        ),
    ]
