# Generated by Django 2.0.5 on 2018-08-13 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de Término')),
                ('tipo', models.CharField(choices=[('FL', 'FERIADO LEGAL'), ('AD', 'ADMINISTRATIVO'), ('LM', 'LICENCIA MÉDICA'), ('CF', 'COMETIDO FUNCIONARIO')], max_length=2, verbose_name='Tipo Ausencia')),
                ('dias', models.PositiveIntegerField(verbose_name='Cantidad de dias')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario', verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Ausencia',
                'verbose_name_plural': 'Ausencias',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
